### ISSUE TITLE
Add support for Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by derekleerock** [derekleerock/Succinct#55]

**Comment by rgravina** [comment]
@derekleerock I've got something working over in this branch I'd like to PR once ready
https://github.com/rgravina/Succinct/tree/support-swift-package-manager

However, two things probably need to happen first:

1) It would be best if [this PR](https://github.com/derekleerock/Succinct/pull/77) is reviewed (and hopefully) merged first if you're OK switching over to SPM, because I (and possbily others using Xcode 13) am having some build issues with Nimble that would require a fix to use `--use-xcframeworks` with Carthage and some project file changes. It could be done. However, if you're planning to merge that anyway then a fix for Xcode 13 and Carthage wouldn't be needed. To get around the problem, that branch is rebased on the top the other PRs branch. I hope that makes sense!

2) I've had to add `import UIKit` or `import Foundation` on most files. For some reason, the `#import <UIKit/UIKit.h>` in `Siccinct.h` is not having any effect. Maybe it's a `Package.swift` issue, but II've found a mention of that [here on Stack Overflow](https://stackoverflow.com/a/67253485). It's probably worth trying to find a way to avoid having to import in all files that reference UIKit or Foundation.
